### PR TITLE
Es6

### PR DESCRIPTION
**Pull request by artisologic**

### CODE REVIEW

**Comment by artisologic** [comment]
@peduarte worth it?

**Comment by peduarte** [comment]
Yeah, why not? hahaha won't make any difference to the final product but its nicer to write es6 😂

**Comment by artisologic** [comment]
I'm just weighing out how much better it is, compared to restricting the extension to latest Chrome version only...

**Comment by peduarte** [comment]
I think you'll find that chances are, your target audience will most likely have an updated version of Chrome

**Comment by artisologic** [comment]
Yeah that's what I was thinking too, given that the audience are devs.

**Pull request merged**
